### ISSUE TITLE
Question about the sourcecode.

### ISSUE THREAD

**Issue by jojonarte** [ooper-shlab/AVCamManual-Swift#4]
What specific function causes the app to improve the preview on darker areas?

**Comment by ooper-shlab** [comment]
Sorry for the late reply, but unfortunately, I do not know any functionality about what you describe.
Hoping you can solve your issue soon.

**Comment by jojonarte** [comment]
I figured it out, it was the Capture preset. Thanks btw. Though I'd like to know more how each preset is set, or how would I be able to do custom preset.
